#配置文件默认dev
spring:
  application.name: analysis-schedule
  profiles:
    active: dev
server:
  port: 8082

mybatis.configuration.mapUnderscoreToCamelCase: true

mapper:
  not-empty: true #
  before: true #
  mappers: tk.mybatis.mapper.common.Mapper #配置的mapper

mybatis-plus:
  mapper-locations: classpath:org/ko/**/*.xml
  type-aliases-package: org.ko.**.domain
