spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      # 数据库 1
      ods:
        url: jdbc:postgresql://gpdb.rds.aliyuncs.com:3432/greenplum
        username:
        password:
        driver-class-name: org.postgresql.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      # 数据库 2
      ads:
        url: jdbc:mysql://mysql.rds.aliyuncs.com:3306/ads?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
        username:
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
