server.servlet:
  context-path: /api

#配置文件默认dev
spring:
  application.name: analysis-app
  profiles:
    active: local
server:
  port: 8081

mybatis.configuration.mapUnderscoreToCamelCase: true

mapper:
  not-empty: true #
  before: true #
  mappers: tk.mybatis.mapper.common.Mapper #配置的mapper

mybatis-plus:
  mapper-locations: classpath:org/ko/segma/rest/**/repository/*.xml  #mapper xml扫描
  type-aliases-package: org.ko.**.domain

