# 端口号
server.port: 8004
# 定义服务名
spring:
  application.name: prototype-admin
  profiles:
    active: dev

master:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///art-prototype
    username: root
    password: tiger

application:
  author: K.O
  email: you_leet@foxmail.com
  url:

# 关闭管理验证
management.security.enabled: false

# 全局日志配置
logging:
  level: debug